import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../data/products.json'
import { fromImageToUrl } from '../utils/urls'

export default function Home() {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         {products.data.map(product=>(
            <div
               key={product.attributes.name}
               className={styles.product}
            >
               <div className={styles.product__Row}>
                  <div className={styles.product__ColImg}>
                     <img src={fromImageToUrl()} alt="" />
                  </div>
                  <div className={styles.product__Col}>
                     {product.attributes.name} {product.attributes.price}
                  </div>
               </div>
            </div>
         ))}
      </div>
   )
}
