import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../data/products.json'
import { fromImageToUrl } from '../utils/urls'

export default function Home() {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         {products.data.map(product=>(
            <div
               key={product.attributes.name}
               className={styles.product}
            >
               <Link href={`/products/${product.attributes.slug}`}>
                  <a>
                     <div className={styles.product__Row}>
                        <div className={styles.product__ColImg}>
                           <img src={fromImageToUrl(product.attributes.image.data.attributes)} alt="" />
                        </div>
                        <div className={styles.product__Col}>
                           {product.attributes.name} {product.attributes.price}
                        </div>
                     </div>
                  </a>
               </Link>
            </div>
         ))}
      </div>
   )
}
